export const numberone = {
    id: 'about',
    lightBg : false,
    lightText : true,
    lightTextDesc: true,
    topLine: 'First-Class Burger',
    Headline: 'We serve the most tasty Burgers and Fries for every budget',
    description: 'Get access to our walk-in locations through our mobile apps, you can also place your orders online and have delivered within minutes',
    buttonLabel: 'Get Started',
    imgStart:  false,
    img: require('../../Images/transfood.png'),
    alt: 'bike',
    dark: true,
    primary: true,
    darktext: false,
};

export const numbertwo = {
    id: 'services',
    lightBg : true,
    lightText : false,
    lightTextDesc: false,
    topLine: 'Premuim Burger',
    Headline: 'we serve the most tasty Burgers and Fries for every budget',
    description: 'Get access to our walk-in locations through our mobile apps, you can also place your orders online and have delivered within minutes',
    buttonLabel: 'Learn More',
    imgStart:  false,
    img: require('../../Images/hungry.png'),
    alt: 'bike',
    dark: false,
    primary: false,
    darktext: true,
};

export const numberthree = {
    id: 'request',
    lightBg : false,
    lightText : true,
    lightTextDesc: false,
    topLine: '24/7 delivery access',
    Headline: 'We deliver anywhere, anytime across lagos',
    description: 'Place your orders and input your location and have your buger delivered in a jiffy',
    buttonLabel: 'Get Started',
    imgStart:  false,
    img: require('../../Images/sweet.png'),
    alt: 'bike',
    dark: true,
    primary: true,
    darktext: false,
}